language: python
python:
  - "2.7"
  - "3.6"
before_install:
  # Install python packages through miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --add channels conda-forge
  - conda update -q conda
  - conda create -n test-environment pip python=$TRAVIS_PYTHON_VERSION numpy nose uncertainties
  - source activate test-environment
  - pip install -q coverage coveralls
install:
  - python setup.py build
  - pip install . 
script:
  - nosetests benta tests -v --with-doctest --with-coverage --cover-package=benta
after_success:
  - coveralls
notifications:
  email: false   
